name: publish
on:
  push:
  workflow_dispatch:
env:
  GITHUB_REPOSITORY: ${{ github.repository }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_BUILD_NUMBER: ${{github.run_number}}
  GITHUB_ACTOR: ${{ github.actor }}

jobs:
  publish:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - run: chmod +x ./gradlew

      - run: git tag ${{github.run_number}}

      - run: ./gradlew publish

      - name: Publish
        run: |
          function mirror() {
            echo "---"
            echo $1
            echo $2
            echo $3
            artifact=$1
            repoUrl=$2
            artifactId=$3
            rm -rf _work
            mkdir _work
            cd _work
            git init
            git config --global user.name "${{ github.actor }}"
            git config --global user.email "${{ github.actor }}@users.noreply.github.com"
#            mvn org.apache.maven.plugins:maven-dependency-plugin:3.4.0:get --quiet --update-snapshots -Dartifact="$artifact" -DremoteRepositories="$repoUrl" -Dmaven.repo.local="." -Dmaven.home="."
            mv ../published/* .
            git add .
            git commit -m "install done" --quiet
            git branch $artifactId --quiet
            git switch $artifactId --quiet
            git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} $artifactId --force && true --quiet
            cd ..
          }
          mkdir libraries || true
          echo "com.github.io.github.bloepiloepi:MinestomPvP:${{github.run_number}}
          https://\$_ACTOR:\$_TOKEN@maven.pkg.github.com/FreedyPlugins/MinestomPVP" > ./libraries/release

          cd libraries
          for filename in *; do
          rm -rf $filename-clone
          cp -r $filename $filename-clone
          filename=$filename-clone
          artifact=$(head -n 1 $filename)
          tail -n +2 "$filename" > $filename-clone
          rm -r $filename
          mv $filename-clone $filename
          echo $(sed ':a;N;$!ba;s/\n/,/g' $filename) > $filename
          repoUrl=$(head $filename)
          echo $repoUrl > $filename
          echo $(sed "s/\$_ACTOR/$GITHUB_ACTOR/g" $filename) > $filename
          echo $(sed "s/\$_TOKEN/$GITHUB_TOKEN/g" $filename) > $filename
          repoUrl=$(head $filename)
          cd ..
          mirror "$artifact" "$repoUrl" $(basename $filename '-clone')
          cd libraries
          done
          cd ..